TEST CI 1

diff --git a/core/Dockerfile b/core/Dockerfile
--- a/core/Dockerfile
+++ b/core/Dockerfile
@@ -29,13 +29,21 @@ ARG TARGETVARIANT
 # The format can be invalid if someone is build BlueOS without a tag as reference
 ARG GIT_DESCRIBE_TAGS
 ENV GIT_DESCRIBE_TAGS=${GIT_DESCRIBE_TAGS:-0.0.0-0-g00000000}
+
+RUN echo "GIT_DESCRIBE_TAGS is set to: $GIT_DESCRIBE_TAGS"
+
+# Check if GIT_DESCRIBE_TAGS is empty
 RUN [ -z "$GIT_DESCRIBE_TAGS" ] \
-    && echo "GIT_DESCRIBE_TAGS argument not provided." \
-    && echo "Use: --build-arg GIT_DESCRIBE_TAGS=\$(git describe --tags --long --always)" \
-    && exit 1 \
-    || /bin/bash -c "[[ ! $GIT_DESCRIBE_TAGS =~ -[0-9]+-g[a-f0-9]{8}$ ]]" \
-    && echo "Invalid format: $GIT_DESCRIBE_TAGS (E.g: <TAG>-<COMMIT_NUMBER>-g<SHORT_HASH>)" \
-    && exit 1 || exit 0
+    &&  echo "GIT_DESCRIBE_TAGS argument not provided."; \
+    &&  echo "Use: --build-arg GIT_DESCRIBE_TAGS=\$(git describe --tags --long --always)"; \
+    &&  exit 1; \
+    || exit 0
+
+# Validate the format of GIT_DESCRIBE_TAGS
+RUN /bin/bash -c "[[ ! $GIT_DESCRIBE_TAGS =~ -[0-9]+-g[a-f0-9]{8}$ ]]" \
+    &&  echo "Invalid format: $GIT_DESCRIBE_TAGS (E.g: <TAG>-<COMMIT_NUMBER>-g<SHORT_HASH>)"; \
+    &&  exit 1; \
+    || exit 0
 
 # Set these arguments as environment variables
 ENV TARGETARCH=${TARGETARCH}
